---
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: main.go
    binary: kubenurse
    id: kubenurse
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - kubenurse
    image_templates:
      - "postfinance/kubenurse:latest"
      - "postfinance/kubenurse:{{ .Tag }}"
    dockerfile: Dockerfile
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
